// - LOGIN
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN = 'LOGIN';
export const LOGIN_START = 'LOGIN_START';
export const AUTH_LOGIN_LOADING = 'AUTH_LOGIN_LOADING';

export const CALENDAR_VIEW_MODE = 'CALENDAR_VIEW_MODE';
export const CALENDAR_MODE_SUCCESS = 'CALENDAR_MODE_SUCCESS';

export const FETCH_MYVANIDAY_HOME_DATA = 'FETCH_MYVANIDAY_HOME_DATA';
export const FETCH_MYVANIDAY_HOME_LOADING = 'FETCH_MYVANIDAY_HOME_LOADING';
export const FETCH_MYVANIDAY_HOME_ERROR = 'FETCH_MYVANIDAY_HOME_ERROR';
export const FETCH_MYVANIDAY_HOME_SUCCESS = 'FETCH_MYVANIDAY_HOME_SUCCESS';
// - RESET ALL STORE
export const RESET_STORE = 'RESET_STORE';
