// - LOGIN
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN_START = 'LOGIN_START';

// - LOGOUT
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_ERROR = 'LOGOUT_ERROR';
export const LOGOUT_START = 'LOGOUT_START';

// - REGISTER
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';
export const REGISTER_START = 'REGISTER_START';
export const SAVE_PROFILE_IMAGE = 'SAVE_PROFILE_IMAGE';
export const SAVE_PROFILE_NAME = 'SAVE_PROFILE_NAME';
export const RESET_STORE = 'RESET_STORE';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
